enum TestId {
  METAMASK_CONNECT_BUTTON,
  METAMASK_CONNECTED,
  REGISTER_TOKEN_BUTTON,
  REGISTER_TOKEN_MODAL,
  REGISTER_TOKEN_FORM_FIELD_NAME,
  REGISTER_TOKEN_FORM_FIELD_SYMBOL,
  REGISTER_TOKEN_FORM_FIELD_SUPPLY,
  REGISTER_TOKEN_FORM_FIELD_CAP,
  REGISTER_TOKEN_FORM_FIELD_DAILY_MINT_LIMIT,
}

export default TestId
