enum TestId {
  ACCOUNT_CREATE_BUTTON,
  ACCOUNT_CREATE_DIALOG_OK_BUTTON,
  ACCOUNT_CREATE_NAME_INPUT,
  ACCOUNT_CREATE_PASSWORD_INPUT,
  ACCOUNT_IMPORT_BUTTON,
  ACCOUNT_IMPORT_FILE_INPUT,
  ACCOUNT_IMPORT_PASSWORD_INPUT,
  TRANSFER_BUTTON,
  TRANSFER_ADDRESS_INPUT,
  TRANSFER_AMOUNT_INPUT,
}

export default TestId
