describe('Multistep form step-2', () => {
  before(() => {
    cy.changeMetamaskNetwork('goerli')
    cy.visit('/')
    cy.get('#connectButton').click()
    cy.acceptMetamaskAccess()
    cy.get('#sendingSubnet').click()
    cy.get('.ant-select-item-option-content').contains('Topos').click()
    cy.allowMetamaskToSwitchNetwork()
    cy.get('#nextButton').click()
    cy.get('#token').click()
    cy.get('#token_list')
      .parent()
      .find('.ant-select-item-option-content')
      .contains('TST')
      .click()
    cy.get('#receivingSubnet').click()
    cy.get('#receivingSubnet_list')
      .parent()
      .find('.ant-select-item-option-content')
      .contains('Incal')
      .click()
    cy.get('#recipientAddress').type('4aab25b4fad0beaac466050f3a7142a502f4cf0a')
    cy.get('#amount').type('1')
    cy.get('#nextButton').click()
  })

  it('should request allowance approval and sendToken transaction signature', () => {
    cy.confirmMetamaskPermissionToSpend()
    cy.confirmMetamaskTransaction()
  })
})
