import { SUCCESS } from '../../../src/constants/wordings'

describe('Cross-subnet Message', () => {
  it('should be able to send TST from Incal to Topos', () => {
    cy.visit('/')
    cy.wait(500)
    cy.get('#connectButton').click()
    cy.acceptMetamaskAccess()

    // Register TST on Topos
    cy.get('#sendingSubnet').click()
    cy.get('.ant-select-item-option-content').contains('Topos').click()
    cy.allowMetamaskToAddAndSwitchNetwork()
    cy.get('#nextButton').click()
    cy.get('#token').click()
    cy.wait(500)
    cy.get('#registerTokenButton').click()
    cy.wait(500)
    cy.get('#form_in_modal_name').type('Test')
    cy.get('#form_in_modal_symbol').type('TST')
    cy.wait(500)
    cy.get('#registerButton').click()
    cy.confirmMetamaskTransaction()
    cy.get('.ant-message-notice-success')
      .contains(SUCCESS.REGISTERED_TOKEN)
      .should('be.visible')

    // Register TST on Incal
    cy.visit('/')
    cy.wait(500)
    cy.get('#sendingSubnet').click()
    cy.get('.ant-select-item-option-content').contains('Incal').click()
    cy.allowMetamaskToAddAndSwitchNetwork()
    cy.get('#nextButton').click()
    cy.get('#token').click()
    cy.wait(500)
    cy.get('#registerTokenButton').click()
    cy.wait(500)
    cy.get('#form_in_modal_name').type('Test')
    cy.get('#form_in_modal_symbol').type('TST')
    cy.wait(500)
    cy.get('#registerButton').click()
    cy.confirmMetamaskTransaction()
    cy.get('.ant-message-notice-success')
      .contains(SUCCESS.REGISTERED_TOKEN)
      .should('be.visible')

    // Send TST
    cy.wait(500)
    cy.get('#token').click()
    cy.get('#token_list')
      .parent()
      .find('.ant-select-item-option-content')
      .contains('TST')
      .click()
    cy.get('#receivingSubnet').click()
    cy.wait(500)
    cy.get('#receivingSubnet_list')
      .parent()
      .find('.ant-select-item-option-content')
      .contains('Topos')
      .click()
    cy.get('#recipientAddress').type(
      '0x4aab25b4fad0beaac466050f3a7142a502f4cf0a'
    )
    cy.get('#amount').type('1')
    cy.get('#nextButton').click()

    // Checks
    cy.get('#executeStep0').find('.ant-spin').should('be.visible')
    cy.get('#executeStep1').find('.ant-spin').should('not.exist')
    cy.get('#executeStep2').find('.ant-spin').should('not.exist')
    cy.confirmMetamaskPermissionToSpend('1')
    cy.get('#executeStep1').find('.ant-spin').should('be.visible')
    cy.get('#executeStep0').find('.ant-spin').should('not.exist')
    cy.get('#executeStep2').find('.ant-spin').should('not.exist')
    cy.confirmMetamaskTransaction()
    cy.get('#executeStep2').find('.ant-spin').should('be.visible')
    cy.get('#executeStep0').find('.ant-spin').should('not.exist')
    cy.get('#executeStep1').find('.ant-spin').should('not.exist')
    cy.get('.ant-result-success', { timeout: 60000 })
      .find('.ant-result-subtitle')
      .should('be.visible')
      .and('have.text', 'Transaction was submitted on Topos')
  })
})
